### ISSUE TITLE
Rails s, returns error "wrong argument type Module (expected Class) (TypeError)"

### ISSUE THREAD

**Issue by michaelnwani** [adiastyle/spree-stripe#3]
After I install the gem, when I try to get my server up with rails s, I'm treated with this error:

"/Users/michaelnwani/.rvm/gems/ruby-1.9.3-p194/bundler/gems/spree-stripe-d55e8438fd03/app/models/gateway/stripe.rb":1":in `<top (required)>': wrong argument type Module (expected Class) (TypeError)"

These are the top lines of stripe.rb: 

"module Spree
    class Gateway::Stripe < Gateway
      preference :login, :string"

Help would be greatly appreciated.

Also I am running Rails 3.2.3, and Spree 1.1.1

**Comment by beingben** [comment]
See the commit I put in for the fix: https://github.com/beingben/spree-stripe/commit/eabf73fab9bfcc3a5995563977f474a96b385178
